FROM node:16.13.2-alpine as build

WORKDIR /app

COPY package-lock.json package-lock.json
COPY package.json package.json

RUN npm ci --production --ignore-scripts

COPY . .

RUN npm run build

FROM nginx:1.21.5-alpine

COPY --from=build /app/build /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]
